spring.datasource.url=jdbc:postgresql://localhost:5432/welcome
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=steampunk
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true